import { StyleSheet, Dimensions } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8f9fa',
    padding: 16,
  },
  profileContainer: {
    backgroundColor: '#FFFFFF',
    padding: 24,
    margin: 16,
    borderRadius: 24,
    shadowColor: '#8641f4',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 8,
    borderWidth: 1,
    borderColor: '#F0F2FF',
  },
  profileHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 24,
  },
  avatarContainer: {
    position: 'relative',
    marginRight: 16,
  },
  avatarGradient: {
    width: 80,
    height: 80,
    borderRadius: 40,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#8641f4',
    shadowColor: '#8641f4',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
      avatarText: {
        color: '#FFFFFF',
        fontSize: 20,
        fontWeight: 'bold',
        fontFamily: 'Nunito-Bold',
      },  verifiedBadge: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    backgroundColor: '#4ECDC4',
    width: 24,
    height: 24,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  verifiedIcon: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: 'bold',
  },
  profileInfo: {
    flex: 1,
  },
  nameContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  userName: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#2D3748',
    marginRight: 8,
    fontFamily: 'Nunito-Bold',
  },
  editButton: {
    padding: 6,
    backgroundColor: '#F7FAFC',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  editIcon: {
    fontSize: 14,
    color: '#8641f4',
  },
  userTitle: {
    fontSize: 14,
    color: '#718096',
    marginBottom: 12,
    fontWeight: '500',
  },
  ratingContainer: {
    alignItems: 'flex-start',
  },
  ratingBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF9E6',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#FFE999',
  },
  ratingStar: {
    fontSize: 14,
    marginRight: 4,
  },
  overallRating: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#D97706',
  },
  ratingMax: {
    fontSize: 12,
    color: '#D97706',
    marginLeft: 2,
  },
  ratingText: {
    fontSize: 12,
    color: '#718096',
    marginTop: 2,
  },
  skillsContainer: {
    marginBottom: 24,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#2D3748',
  },
  skillPill: {
    backgroundColor: '#EDF2F7',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
  },
  skillPillText: {
    fontSize: 12,
    color: '#4A5568',
    fontWeight: '600',
  },
  skillsGrid: {
    flexDirection: 'row',
    gap: 16,
  },
  skillColumn: {
    flex: 1,
    gap: 12,
  },
  statsContainer: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 20,
  },
  statCard: {
    flex: 1,
    padding: 16,
    borderRadius: 16,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  statCardPrimary: {
    backgroundColor: '#8641f4',
  },
  statCardSuccess: {
    backgroundColor: '#4ECDC4',
  },
  statCardWarning: {
    backgroundColor: '#FF6B6B',
  },
  statIcon: {
    fontSize: 20,
    marginBottom: 8,
    color: '#FFFFFF',
  },
  statNumber: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 2,
  },
  statLabel: {
    fontSize: 12,
    color: '#FFFFFF',
    fontWeight: '600',
    marginBottom: 2,
  },
  statSubtext: {
    fontSize: 10,
    color: 'rgba(255,255,255,0.8)',
  },
  achievementContainer: {
    alignItems: 'center',
  },
  achievementBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF9E6',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: '#FFE999',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  achievementIcon: {
    fontSize: 24,
    marginRight: 12,
  },
  achievementText: {
    flex: 1,
  },
  achievementTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#D97706',
    marginBottom: 2,
  },
  achievementDesc: {
    fontSize: 12,
    color: '#B45309',
  },
  actionsContainer: {
    backgroundColor: '#ffffff',
    padding: 20,
    margin: 10,
    borderRadius: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 3,
  },
  actionsGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  actionButton: {
    flex: 1,
    marginHorizontal: 5,
    padding: 15,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionIcon: {
    fontSize: 24,
    marginBottom: 5,
  },
  actionText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '600',
    textAlign: 'center',
  },
  graphContainer: {
    backgroundColor: '#ffffff',
    padding: 20,
    margin: 10,
    borderRadius: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 3,
  },
  chart: {
    borderRadius: 16,
  },
  sessionsContainer: {
    backgroundColor: '#ffffff',
    padding: 20,
    margin: 10,
    borderRadius: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 3,
  },
  seeAllText: {
    color: '#8641f4',
    fontWeight: '600',
  },
  skillContainer: {
    marginBottom: 12,
  },
  skillHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  skillInfo: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  skillIcon: {
    fontSize: 16,
    marginRight: 6,
  },
  skillName: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
  },
  ratingNumber: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#8641f4',
  },
  progressBarContainer: {
    position: 'relative',
    marginBottom: 2,
  },
  progressBarBackground: {
    height: 8,
    backgroundColor: '#f0f0f0',
    borderRadius: 4,
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    borderRadius: 4,
  },
  progressMarkers: {
    position: 'absolute',
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    top: 2,
    paddingHorizontal: 2,
  },
  marker: {
    width: 2,
    height: 4,
    backgroundColor: 'rgba(255,255,255,0.5)',
    borderRadius: 1,
  },
  skillLevelContainer: {
    alignSelf: 'flex-end',
  },
  skillLevel: {
    fontSize: 10,
    fontWeight: '600',
    textTransform: 'uppercase',
  },

  // Compact SkillMeter Styles
  compactContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f8f9fa',
    padding: 6,
    borderRadius: 8,
    margin: 1,
  },
  compactSmall: {
    padding: 4,
  },
  compactMedium: {
    padding: 6,
  },
  compactLarge: {
    padding: 10,
  },
  compactIcon: {
    marginRight: 6,
  },
  compactIconText: {
    fontSize: 14,
  },
  compactInfo: {
    flex: 1,
  },
  compactSkillName: {
    fontSize: 12,
    fontWeight: '500',
    color: '#333',
    marginBottom: 2,
  },
  compactProgressBar: {
    height: 4,
    backgroundColor: '#e0e0e0',
    borderRadius: 2,
    overflow: 'hidden',
  },
  compactProgressFill: {
    height: '100%',
    borderRadius: 2,
  },
  compactRating: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#8641f4',
    marginLeft: 6,
    minWidth: 25,
    textAlign: 'right',
  },
});
